# dbt_project/dbt_project.yml

name: 'nfl_batchgineering'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'nfl_batchgineering'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  nfl_batchgineering:
  # Config indicated by + and applies to all files under models/example/
    1_staging:
      +materialized: view
    2_intermediate:
      +materialized: view

# Seeds configuration
# seeds:

# Macros for common patterns
vars:
  # Current season for incremental models
  current_season: 2025
  # Number of seasons to look back for features
  lookback_seasons: 10
  # Minimum games for statistical significance
  min_games_threshold: 8
